# Generated by Django 4.2.27 on 2025-12-19 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('isbn', models.CharField(help_text='Enter ISBN-10 or ISBN-13', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be 10 or 13 digits.', regex='^\\d{10}(\\d{3})?$')])),
                ('page_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('published_date', models.DateField()),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science-fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('technology', 'Technology'), ('self-help', 'Self-Help'), ('children', 'Children'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('total_copies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title', 'author'], name='books_book_title_b7b426_idx'), models.Index(fields=['genre', 'available_copies'], name='books_book_genre_f2efe5_idx')],
            },
        ),
    ]
